spring.application.name=scm
spring.datasource.url=jdbc:mysql://localhost:3306/scm
spring.datasource.username=root
spring.datasource.password=root

#jpa-config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update